[theme]
base = "light"
primaryColor = "#8BA834"
backgroundColor = "#FAFAF5"
secondaryBackgroundColor = "#F0F0EA"
textColor = "#2C2C2C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
